//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MemberRole
    {
        public int MemberRoleID { get; set; }
        public Nullable<int> memberId { get; set; }
        public Nullable<int> RoleId { get; set; }
    }
}
