//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingStore.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public int ProductId { get; set; }
        [DisplayName("Product Name")]
        public string ProductName { get; set; }
        [DisplayName("Category Name")]
        public Nullable<int> CategoryId { get; set; }
        [DisplayName("Is the product active?")]
        public Nullable<bool> IsActive { get; set; }
        [DisplayName("Is the product to be deleted?")]
        public Nullable<bool> IsDelete { get; set; }
        [DisplayName("The created date")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        [DisplayName("the modified date")]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Description { get; set; }
        [DisplayName("Image")]
        public string ProductImage { get; set; }
        [DisplayName("Is the product featured?")]
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Cart> Tbl_Cart { get; set; }
        public Tbl_Category Tbl_Category { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
        public Tbl_Product()
        {
            this.Tbl_Cart = new HashSet<Tbl_Cart>();
        }

    }
}
